// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (user_id, key_hash, label, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, key_hash, label, created_at
`

type CreateApiKeyParams struct {
	UserID    int64
	KeyHash   string
	Label     pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.UserID,
		arg.KeyHash,
		arg.Label,
		arg.CreatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	ID        string
	UserID    int64
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash)
VALUES ($1, $2)
RETURNING id, username, password_hash
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const deleteApiKeyForUser = `-- name: DeleteApiKeyForUser :execrows
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteApiKeyForUserParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteApiKeyForUser(ctx context.Context, arg DeleteApiKeyForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApiKeyForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteApiKeysByUser = `-- name: DeleteApiKeysByUser :exec
DELETE FROM api_keys WHERE user_id = $1
`

func (q *Queries) DeleteApiKeysByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteApiKeysByUser, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, user_id, key_hash, label, created_at FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, created_at, expires_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const listApiKeysByUser = `-- name: ListApiKeysByUser :many
SELECT id, label, created_at FROM api_keys WHERE user_id = $1 ORDER BY created_at, id
`

type ListApiKeysByUserRow struct {
	ID        int64
	Label     pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListApiKeysByUser(ctx context.Context, userID int64) ([]ListApiKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiKeysByUserRow
	for rows.Next() {
		var i ListApiKeysByUserRow
		if err := rows.Scan(&i.ID, &i.Label, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE username = $1
`

type UpdateUserPasswordParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Username, arg.PasswordHash)
	return err
}

const updateUserPasswordByID = `-- name: UpdateUserPasswordByID :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordByIDParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPasswordByID(ctx context.Context, arg UpdateUserPasswordByIDParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordByID, arg.ID, arg.PasswordHash)
	return err
}
