// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal_status_update.sql

package db

import (
	"context"
)

const addGoalStatusUpdate = `-- name: AddGoalStatusUpdate :one
INSERT INTO goal_status_updates (goal_id, body)
SELECT $1, $3 FROM goals WHERE id = $1 AND user_id = $2
RETURNING id, goal_id, body, created_at
`

type AddGoalStatusUpdateParams struct {
	GoalID int64
	UserID int64
	Body   string
}

func (q *Queries) AddGoalStatusUpdate(ctx context.Context, arg AddGoalStatusUpdateParams) (GoalStatusUpdate, error) {
	row := q.db.QueryRow(ctx, addGoalStatusUpdate, arg.GoalID, arg.UserID, arg.Body)
	var i GoalStatusUpdate
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGoalStatusUpdate = `-- name: DeleteGoalStatusUpdate :one
DELETE FROM goal_status_updates su
USING goals g
WHERE su.id = $1 AND su.goal_id = g.id AND g.user_id = $2
RETURNING su.id
`

type DeleteGoalStatusUpdateParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteGoalStatusUpdate(ctx context.Context, arg DeleteGoalStatusUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteGoalStatusUpdate, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLatestGoalStatusUpdate = `-- name: GetLatestGoalStatusUpdate :one
SELECT id, goal_id, body, created_at FROM goal_status_updates
WHERE goal_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestGoalStatusUpdate(ctx context.Context, goalID int64) (GoalStatusUpdate, error) {
	row := q.db.QueryRow(ctx, getLatestGoalStatusUpdate, goalID)
	var i GoalStatusUpdate
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listGoalStatusUpdates = `-- name: ListGoalStatusUpdates :many
SELECT su.id, su.goal_id, su.body, su.created_at FROM goal_status_updates su
JOIN goals g ON g.id = su.goal_id
WHERE su.goal_id = $1 AND g.user_id = $2
ORDER BY su.created_at DESC, su.id DESC
`

type ListGoalStatusUpdatesParams struct {
	GoalID int64
	UserID int64
}

func (q *Queries) ListGoalStatusUpdates(ctx context.Context, arg ListGoalStatusUpdatesParams) ([]GoalStatusUpdate, error) {
	rows, err := q.db.Query(ctx, listGoalStatusUpdates, arg.GoalID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalStatusUpdate
	for rows.Next() {
		var i GoalStatusUpdate
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestGoalStatusUpdates = `-- name: ListLatestGoalStatusUpdates :many
SELECT DISTINCT ON (goal_id) id, goal_id, body, created_at
FROM goal_status_updates
WHERE goal_id = ANY($1::bigint[])
ORDER BY goal_id, created_at DESC, id DESC
`

func (q *Queries) ListLatestGoalStatusUpdates(ctx context.Context, dollar_1 []int64) ([]GoalStatusUpdate, error) {
	rows, err := q.db.Query(ctx, listLatestGoalStatusUpdates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalStatusUpdate
	for rows.Next() {
		var i GoalStatusUpdate
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoalStatusUpdate = `-- name: UpdateGoalStatusUpdate :one
UPDATE goal_status_updates su SET body = $3
FROM goals g
WHERE su.id = $1 AND su.goal_id = g.id AND g.user_id = $2
RETURNING su.id, su.goal_id, su.body, su.created_at
`

type UpdateGoalStatusUpdateParams struct {
	ID     int64
	UserID int64
	Body   string
}

func (q *Queries) UpdateGoalStatusUpdate(ctx context.Context, arg UpdateGoalStatusUpdateParams) (GoalStatusUpdate, error) {
	row := q.db.QueryRow(ctx, updateGoalStatusUpdate, arg.ID, arg.UserID, arg.Body)
	var i GoalStatusUpdate
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}
