// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (user_id, name, description, due, state, position)
VALUES ($1, $2, $3, $4, 'incubating',
  COALESCE((SELECT MAX(position) + 1 FROM goals WHERE user_id = $1 AND state = 'incubating'), 0))
RETURNING id, user_id, name, description, due, state, position
`

type CreateGoalParams struct {
	UserID      int64
	Name        string
	Description string
	Due         pgtype.Timestamptz
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Due,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.State,
		&i.Position,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :one
DELETE FROM goals WHERE id = $1 AND user_id = $2 RETURNING id
`

type DeleteGoalParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteGoal, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getGoal = `-- name: GetGoal :one
SELECT id, user_id, name, description, due, state, position FROM goals WHERE id = $1 AND user_id = $2
`

type GetGoalParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.State,
		&i.Position,
	)
	return i, err
}

const listGoalStateGroup = `-- name: ListGoalStateGroup :many
SELECT id, user_id, name, description, due, state, position FROM goals
WHERE user_id = $1 AND state = $2
ORDER BY position, id
FOR UPDATE
`

type ListGoalStateGroupParams struct {
	UserID int64
	State  string
}

func (q *Queries) ListGoalStateGroup(ctx context.Context, arg ListGoalStateGroupParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoalStateGroup, arg.UserID, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Due,
			&i.State,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, user_id, name, description, due, state, position FROM goals
WHERE user_id = $1
ORDER BY
  CASE state
    WHEN 'in_progress' THEN 1
    WHEN 'incubating' THEN 2
    WHEN 'hold'       THEN 3
    WHEN 'completed'  THEN 4
    WHEN 'archived'   THEN 5
    ELSE 6
  END,
  position, id
`

func (q *Queries) ListGoals(ctx context.Context, userID int64) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Due,
			&i.State,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGoalState = `-- name: SetGoalState :one
UPDATE goals AS g
SET state = $3,
    position = COALESCE((SELECT MAX(g2.position) + 1 FROM goals g2 WHERE g2.user_id = $2 AND g2.state = $3), 0)
WHERE g.id = $1 AND g.user_id = $2 AND g.state <> $3
RETURNING id, user_id, name, description, due, state, position
`

type SetGoalStateParams struct {
	ID     int64
	UserID int64
	State  string
}

func (q *Queries) SetGoalState(ctx context.Context, arg SetGoalStateParams) (Goal, error) {
	row := q.db.QueryRow(ctx, setGoalState, arg.ID, arg.UserID, arg.State)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.State,
		&i.Position,
	)
	return i, err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET name = $3, description = $4, due = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, description, due, state, position
`

type UpdateGoalParams struct {
	ID          int64
	UserID      int64
	Name        string
	Description string
	Due         pgtype.Timestamptz
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Due,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.State,
		&i.Position,
	)
	return i, err
}

const updateGoalPosition = `-- name: UpdateGoalPosition :exec
UPDATE goals SET position = $3 WHERE id = $1 AND user_id = $2
`

type UpdateGoalPositionParams struct {
	ID       int64
	UserID   int64
	Position pgtype.Int4
}

func (q *Queries) UpdateGoalPosition(ctx context.Context, arg UpdateGoalPositionParams) error {
	_, err := q.db.Exec(ctx, updateGoalPosition, arg.ID, arg.UserID, arg.Position)
	return err
}
