// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        int64
	UserID    int64
	KeyHash   string
	Label     pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Goal struct {
	ID          int64
	UserID      int64
	Name        string
	Description string
	Due         pgtype.Timestamptz
	State       string
	Position    pgtype.Int4
}

type GoalStatusUpdate struct {
	ID        int64
	GoalID    int64
	Body      string
	CreatedAt pgtype.Timestamptz
}

type PlanEntry struct {
	UserID         int64
	Day            pgtype.Date
	ID             int32
	TaskID         pgtype.Int8
	Name           pgtype.Text
	StartMinute    pgtype.Int2
	DurationMinute int16
	Position       int16
}

type Pomodoro struct {
	ID       int64
	UserID   int64
	TaskID   int64
	StartAt  pgtype.Timestamptz
	EndAt    pgtype.Timestamptz
	Complete bool
}

type Session struct {
	ID        string
	UserID    int64
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Task struct {
	ID          int64
	Name        string
	Description string
	Due         pgtype.Timestamptz
	ParentID    pgtype.Int8
	UserID      int64
	CompletedAt pgtype.Timestamptz
	Estimate    int16
	Position    int32
	SnoozeUntil pgtype.Timestamptz
	GoalID      pgtype.Int8
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
}
