// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlanEntriesFromMinute = `-- name: DeletePlanEntriesFromMinute :execrows
DELETE FROM plan_entries WHERE user_id = $1 AND day = $2 AND start_minute >= $3 AND task_id IS NOT NULL
`

type DeletePlanEntriesFromMinuteParams struct {
	UserID      int64
	Day         pgtype.Date
	StartMinute pgtype.Int2
}

func (q *Queries) DeletePlanEntriesFromMinute(ctx context.Context, arg DeletePlanEntriesFromMinuteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlanEntriesFromMinute, arg.UserID, arg.Day, arg.StartMinute)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlanEntry = `-- name: DeletePlanEntry :one
DELETE FROM plan_entries WHERE user_id = $1 AND day = $2 AND id = $3 RETURNING id
`

type DeletePlanEntryParams struct {
	UserID int64
	Day    pgtype.Date
	ID     int32
}

func (q *Queries) DeletePlanEntry(ctx context.Context, arg DeletePlanEntryParams) (int32, error) {
	row := q.db.QueryRow(ctx, deletePlanEntry, arg.UserID, arg.Day, arg.ID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getPlanEntry = `-- name: GetPlanEntry :one
SELECT user_id, day, id, task_id, name, start_minute, duration_minute, position FROM plan_entries WHERE user_id = $1 AND day = $2 AND id = $3
`

type GetPlanEntryParams struct {
	UserID int64
	Day    pgtype.Date
	ID     int32
}

func (q *Queries) GetPlanEntry(ctx context.Context, arg GetPlanEntryParams) (PlanEntry, error) {
	row := q.db.QueryRow(ctx, getPlanEntry, arg.UserID, arg.Day, arg.ID)
	var i PlanEntry
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.StartMinute,
		&i.DurationMinute,
		&i.Position,
	)
	return i, err
}

const insertPlanEntry = `-- name: InsertPlanEntry :one
INSERT INTO plan_entries (user_id, day, id, task_id, name, start_minute, duration_minute, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, COALESCE((SELECT MAX(position)+1 FROM plan_entries WHERE user_id = $1 AND day = $2), 0))
RETURNING user_id, day, id, task_id, name, start_minute, duration_minute, position
`

type InsertPlanEntryParams struct {
	UserID         int64
	Day            pgtype.Date
	ID             int32
	TaskID         pgtype.Int8
	Name           pgtype.Text
	StartMinute    pgtype.Int2
	DurationMinute int16
}

func (q *Queries) InsertPlanEntry(ctx context.Context, arg InsertPlanEntryParams) (PlanEntry, error) {
	row := q.db.QueryRow(ctx, insertPlanEntry,
		arg.UserID,
		arg.Day,
		arg.ID,
		arg.TaskID,
		arg.Name,
		arg.StartMinute,
		arg.DurationMinute,
	)
	var i PlanEntry
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.StartMinute,
		&i.DurationMinute,
		&i.Position,
	)
	return i, err
}

const listPlanEntriesForDay = `-- name: ListPlanEntriesForDay :many
SELECT plan_entries.user_id, plan_entries.day, plan_entries.id, plan_entries.task_id, plan_entries.name, plan_entries.start_minute, plan_entries.duration_minute, plan_entries.position,
  (plan_entries.task_id IS NOT NULL AND tasks.completed_at IS NOT NULL) AS completed
FROM plan_entries
LEFT JOIN tasks ON plan_entries.task_id = tasks.id AND tasks.user_id = plan_entries.user_id
WHERE plan_entries.user_id = $1 AND plan_entries.day = $2
ORDER BY plan_entries.start_minute ASC NULLS FIRST, plan_entries.position ASC, plan_entries.id ASC
`

type ListPlanEntriesForDayParams struct {
	UserID int64
	Day    pgtype.Date
}

type ListPlanEntriesForDayRow struct {
	UserID         int64
	Day            pgtype.Date
	ID             int32
	TaskID         pgtype.Int8
	Name           pgtype.Text
	StartMinute    pgtype.Int2
	DurationMinute int16
	Position       int16
	Completed      pgtype.Bool
}

func (q *Queries) ListPlanEntriesForDay(ctx context.Context, arg ListPlanEntriesForDayParams) ([]ListPlanEntriesForDayRow, error) {
	rows, err := q.db.Query(ctx, listPlanEntriesForDay, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlanEntriesForDayRow
	for rows.Next() {
		var i ListPlanEntriesForDayRow
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.ID,
			&i.TaskID,
			&i.Name,
			&i.StartMinute,
			&i.DurationMinute,
			&i.Position,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledDaysForTasks = `-- name: ListScheduledDaysForTasks :many
SELECT DISTINCT task_id, day
FROM plan_entries
WHERE user_id = $1
  AND task_id IS NOT NULL
  AND day >= $2
ORDER BY task_id, day
`

type ListScheduledDaysForTasksParams struct {
	UserID int64
	Day    pgtype.Date
}

type ListScheduledDaysForTasksRow struct {
	TaskID pgtype.Int8
	Day    pgtype.Date
}

func (q *Queries) ListScheduledDaysForTasks(ctx context.Context, arg ListScheduledDaysForTasksParams) ([]ListScheduledDaysForTasksRow, error) {
	rows, err := q.db.Query(ctx, listScheduledDaysForTasks, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduledDaysForTasksRow
	for rows.Next() {
		var i ListScheduledDaysForTasksRow
		if err := rows.Scan(&i.TaskID, &i.Day); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlanEntriesForDay = `-- name: LockPlanEntriesForDay :many
SELECT user_id, day, id, task_id, name, start_minute, duration_minute, position FROM plan_entries WHERE user_id = $1 AND day = $2 FOR UPDATE
`

type LockPlanEntriesForDayParams struct {
	UserID int64
	Day    pgtype.Date
}

func (q *Queries) LockPlanEntriesForDay(ctx context.Context, arg LockPlanEntriesForDayParams) ([]PlanEntry, error) {
	rows, err := q.db.Query(ctx, lockPlanEntriesForDay, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanEntry
	for rows.Next() {
		var i PlanEntry
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.ID,
			&i.TaskID,
			&i.Name,
			&i.StartMinute,
			&i.DurationMinute,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUntimedPlanEntriesForDay = `-- name: LockUntimedPlanEntriesForDay :many
SELECT user_id, day, id, task_id, name, start_minute, duration_minute, position FROM plan_entries WHERE user_id = $1 AND day = $2 AND start_minute IS NULL ORDER BY position, id FOR UPDATE
`

type LockUntimedPlanEntriesForDayParams struct {
	UserID int64
	Day    pgtype.Date
}

func (q *Queries) LockUntimedPlanEntriesForDay(ctx context.Context, arg LockUntimedPlanEntriesForDayParams) ([]PlanEntry, error) {
	rows, err := q.db.Query(ctx, lockUntimedPlanEntriesForDay, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanEntry
	for rows.Next() {
		var i PlanEntry
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.ID,
			&i.TaskID,
			&i.Name,
			&i.StartMinute,
			&i.DurationMinute,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPlanEntryId = `-- name: NextPlanEntryId :one
SELECT COALESCE(MAX(id), 0) + 1 AS next_id FROM plan_entries WHERE user_id = $1 AND day = $2
`

type NextPlanEntryIdParams struct {
	UserID int64
	Day    pgtype.Date
}

func (q *Queries) NextPlanEntryId(ctx context.Context, arg NextPlanEntryIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextPlanEntryId, arg.UserID, arg.Day)
	var next_id int32
	err := row.Scan(&next_id)
	return next_id, err
}

const trimPlanEntryDuration = `-- name: TrimPlanEntryDuration :one
UPDATE plan_entries SET duration_minute = $4 WHERE user_id = $1 AND day = $2 AND id = $3 RETURNING user_id, day, id, task_id, name, start_minute, duration_minute, position
`

type TrimPlanEntryDurationParams struct {
	UserID         int64
	Day            pgtype.Date
	ID             int32
	DurationMinute int16
}

func (q *Queries) TrimPlanEntryDuration(ctx context.Context, arg TrimPlanEntryDurationParams) (PlanEntry, error) {
	row := q.db.QueryRow(ctx, trimPlanEntryDuration,
		arg.UserID,
		arg.Day,
		arg.ID,
		arg.DurationMinute,
	)
	var i PlanEntry
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.StartMinute,
		&i.DurationMinute,
		&i.Position,
	)
	return i, err
}

const updatePlanEntryName = `-- name: UpdatePlanEntryName :one
UPDATE plan_entries SET name = $4 WHERE user_id = $1 AND day = $2 AND id = $3 RETURNING user_id, day, id, task_id, name, start_minute, duration_minute, position
`

type UpdatePlanEntryNameParams struct {
	UserID int64
	Day    pgtype.Date
	ID     int32
	Name   pgtype.Text
}

func (q *Queries) UpdatePlanEntryName(ctx context.Context, arg UpdatePlanEntryNameParams) (PlanEntry, error) {
	row := q.db.QueryRow(ctx, updatePlanEntryName,
		arg.UserID,
		arg.Day,
		arg.ID,
		arg.Name,
	)
	var i PlanEntry
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.StartMinute,
		&i.DurationMinute,
		&i.Position,
	)
	return i, err
}

const updatePlanEntryPosition = `-- name: UpdatePlanEntryPosition :exec
UPDATE plan_entries SET position = $4 WHERE user_id = $1 AND day = $2 AND id = $3
`

type UpdatePlanEntryPositionParams struct {
	UserID   int64
	Day      pgtype.Date
	ID       int32
	Position int16
}

func (q *Queries) UpdatePlanEntryPosition(ctx context.Context, arg UpdatePlanEntryPositionParams) error {
	_, err := q.db.Exec(ctx, updatePlanEntryPosition,
		arg.UserID,
		arg.Day,
		arg.ID,
		arg.Position,
	)
	return err
}

const updatePlanEntryTime = `-- name: UpdatePlanEntryTime :one
UPDATE plan_entries SET start_minute = $4, duration_minute = $5 WHERE user_id = $1 AND day = $2 AND id = $3 RETURNING user_id, day, id, task_id, name, start_minute, duration_minute, position
`

type UpdatePlanEntryTimeParams struct {
	UserID         int64
	Day            pgtype.Date
	ID             int32
	StartMinute    pgtype.Int2
	DurationMinute int16
}

func (q *Queries) UpdatePlanEntryTime(ctx context.Context, arg UpdatePlanEntryTimeParams) (PlanEntry, error) {
	row := q.db.QueryRow(ctx, updatePlanEntryTime,
		arg.UserID,
		arg.Day,
		arg.ID,
		arg.StartMinute,
		arg.DurationMinute,
	)
	var i PlanEntry
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.StartMinute,
		&i.DurationMinute,
		&i.Position,
	)
	return i, err
}

const updatePlanEntryTimeAndPosition = `-- name: UpdatePlanEntryTimeAndPosition :one
UPDATE plan_entries SET start_minute = $4, duration_minute = $5, position = $6 WHERE user_id = $1 AND day = $2 AND id = $3 RETURNING user_id, day, id, task_id, name, start_minute, duration_minute, position
`

type UpdatePlanEntryTimeAndPositionParams struct {
	UserID         int64
	Day            pgtype.Date
	ID             int32
	StartMinute    pgtype.Int2
	DurationMinute int16
	Position       int16
}

func (q *Queries) UpdatePlanEntryTimeAndPosition(ctx context.Context, arg UpdatePlanEntryTimeAndPositionParams) (PlanEntry, error) {
	row := q.db.QueryRow(ctx, updatePlanEntryTimeAndPosition,
		arg.UserID,
		arg.Day,
		arg.ID,
		arg.StartMinute,
		arg.DurationMinute,
		arg.Position,
	)
	var i PlanEntry
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.StartMinute,
		&i.DurationMinute,
		&i.Position,
	)
	return i, err
}
