// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ancestorHasGoal = `-- name: AncestorHasGoal :one
WITH RECURSIVE ancestors AS (
    SELECT t.id, t.parent_id, t.goal_id
      FROM tasks t
      JOIN tasks seed ON t.id = seed.parent_id
     WHERE seed.id = $1 AND seed.user_id = $2 AND t.user_id = $2
    UNION ALL
    SELECT t.id, t.parent_id, t.goal_id
      FROM tasks t
      JOIN ancestors ON t.id = ancestors.parent_id
     WHERE t.user_id = $2
)
SELECT EXISTS (
    SELECT 1 FROM ancestors WHERE goal_id IS NOT NULL
) AS has_goal
`

type AncestorHasGoalParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) AncestorHasGoal(ctx context.Context, arg AncestorHasGoalParams) (bool, error) {
	row := q.db.QueryRow(ctx, ancestorHasGoal, arg.ID, arg.UserID)
	var has_goal bool
	err := row.Scan(&has_goal)
	return has_goal, err
}

const clearSubtreeGoals = `-- name: ClearSubtreeGoals :exec
WITH RECURSIVE descendants AS (
    SELECT tasks.id
      FROM tasks
     WHERE tasks.parent_id = $1 AND tasks.user_id = $2
    UNION ALL
    SELECT t.id
      FROM tasks t
      JOIN descendants d ON t.parent_id = d.id
     WHERE t.user_id = $2
)
UPDATE tasks SET goal_id = NULL
 WHERE tasks.id IN (SELECT id FROM descendants)
   AND tasks.user_id = $2
`

type ClearSubtreeGoalsParams struct {
	ParentID pgtype.Int8
	UserID   int64
}

// Recursive UPDATE that clears goal_id on every descendant of $1 (not
// including $1 itself). Used by UpdateTask on a descent to repair
// pre-existing rows whose goal link violated the invariant.
func (q *Queries) ClearSubtreeGoals(ctx context.Context, arg ClearSubtreeGoalsParams) error {
	_, err := q.db.Exec(ctx, clearSubtreeGoals, arg.ParentID, arg.UserID)
	return err
}

const clearTaskGoal = `-- name: ClearTaskGoal :one
UPDATE tasks SET goal_id = NULL WHERE id = $1 AND user_id = $2 RETURNING id, name, description, due, parent_id, user_id, completed_at, estimate, position, snooze_until, goal_id
`

type ClearTaskGoalParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) ClearTaskGoal(ctx context.Context, arg ClearTaskGoalParams) (Task, error) {
	row := q.db.QueryRow(ctx, clearTaskGoal, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
		&i.UserID,
		&i.CompletedAt,
		&i.Estimate,
		&i.Position,
		&i.SnoozeUntil,
		&i.GoalID,
	)
	return i, err
}

const completeTask = `-- name: CompleteTask :one
UPDATE tasks
SET completed_at = COALESCE(completed_at, NOW())
WHERE id = $1 AND user_id = $2
RETURNING id, name, description, due, parent_id, user_id, completed_at, estimate, position, snooze_until, goal_id
`

type CompleteTaskParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, completeTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
		&i.UserID,
		&i.CompletedAt,
		&i.Estimate,
		&i.Position,
		&i.SnoozeUntil,
		&i.GoalID,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (name, description, due, parent_id, user_id, snooze_until, position)
VALUES ($1, $2, $3, $4, $5, $6,
  COALESCE((SELECT MAX(position) + 1 FROM tasks WHERE user_id = $5 AND parent_id IS NOT DISTINCT FROM $4), 0))
RETURNING id, name, description, due, parent_id, user_id, completed_at, estimate, position, snooze_until, goal_id
`

type CreateTaskParams struct {
	Name        string
	Description string
	Due         pgtype.Timestamptz
	ParentID    pgtype.Int8
	UserID      int64
	SnoozeUntil pgtype.Timestamptz
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Name,
		arg.Description,
		arg.Due,
		arg.ParentID,
		arg.UserID,
		arg.SnoozeUntil,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
		&i.UserID,
		&i.CompletedAt,
		&i.Estimate,
		&i.Position,
		&i.SnoozeUntil,
		&i.GoalID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :one
DELETE FROM tasks WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteTaskParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteTask, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const descendantHasGoal = `-- name: DescendantHasGoal :one
WITH RECURSIVE descendants AS (
    SELECT tasks.id, tasks.goal_id
      FROM tasks
     WHERE tasks.parent_id = $1 AND tasks.user_id = $2
    UNION ALL
    SELECT t.id, t.goal_id
      FROM tasks t
      JOIN descendants d ON t.parent_id = d.id
     WHERE t.user_id = $2
)
SELECT EXISTS (
    SELECT 1 FROM descendants WHERE goal_id IS NOT NULL
) AS has_goal
`

type DescendantHasGoalParams struct {
	ParentID pgtype.Int8
	UserID   int64
}

func (q *Queries) DescendantHasGoal(ctx context.Context, arg DescendantHasGoalParams) (bool, error) {
	row := q.db.QueryRow(ctx, descendantHasGoal, arg.ParentID, arg.UserID)
	var has_goal bool
	err := row.Scan(&has_goal)
	return has_goal, err
}

const getMaxSiblingPosition = `-- name: GetMaxSiblingPosition :one
SELECT COALESCE(MAX(position), -1)::integer AS max_pos
FROM tasks
WHERE user_id = $1 AND parent_id IS NOT DISTINCT FROM $2
`

type GetMaxSiblingPositionParams struct {
	UserID   int64
	ParentID pgtype.Int8
}

func (q *Queries) GetMaxSiblingPosition(ctx context.Context, arg GetMaxSiblingPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxSiblingPosition, arg.UserID, arg.ParentID)
	var max_pos int32
	err := row.Scan(&max_pos)
	return max_pos, err
}

const getParentCompletion = `-- name: GetParentCompletion :one
SELECT completed_at FROM tasks WHERE id = $1 AND user_id = $2
`

type GetParentCompletionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetParentCompletion(ctx context.Context, arg GetParentCompletionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getParentCompletion, arg.ID, arg.UserID)
	var completed_at pgtype.Timestamptz
	err := row.Scan(&completed_at)
	return completed_at, err
}

const getTask = `-- name: GetTask :one
SELECT id, name, description, due, parent_id, user_id, completed_at, estimate, position, snooze_until, goal_id FROM tasks WHERE id = $1 AND user_id = $2
`

type GetTaskParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
		&i.UserID,
		&i.CompletedAt,
		&i.Estimate,
		&i.Position,
		&i.SnoozeUntil,
		&i.GoalID,
	)
	return i, err
}

const hasIncompleteDescendants = `-- name: HasIncompleteDescendants :one
WITH RECURSIVE descendants AS (
    SELECT tasks.id, tasks.completed_at
      FROM tasks
     WHERE tasks.parent_id = $1 AND tasks.user_id = $2
    UNION ALL
    SELECT t.id, t.completed_at
      FROM tasks t
      JOIN descendants d ON t.parent_id = d.id
     WHERE t.user_id = $2
)
SELECT EXISTS (
    SELECT 1 FROM descendants WHERE completed_at IS NULL
) AS has_incomplete
`

type HasIncompleteDescendantsParams struct {
	ParentID pgtype.Int8
	UserID   int64
}

func (q *Queries) HasIncompleteDescendants(ctx context.Context, arg HasIncompleteDescendantsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasIncompleteDescendants, arg.ParentID, arg.UserID)
	var has_incomplete bool
	err := row.Scan(&has_incomplete)
	return has_incomplete, err
}

const listIncompleteDescendantIds = `-- name: ListIncompleteDescendantIds :many
WITH RECURSIVE descendants AS (
    SELECT tasks.id, tasks.completed_at
      FROM tasks
     WHERE tasks.parent_id = $1 AND tasks.user_id = $2
    UNION ALL
    SELECT t.id, t.completed_at
      FROM tasks t
      JOIN descendants d ON t.parent_id = d.id
     WHERE t.user_id = $2
)
SELECT id FROM descendants WHERE completed_at IS NULL ORDER BY id
`

type ListIncompleteDescendantIdsParams struct {
	ParentID pgtype.Int8
	UserID   int64
}

func (q *Queries) ListIncompleteDescendantIds(ctx context.Context, arg ListIncompleteDescendantIdsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listIncompleteDescendantIds, arg.ParentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiblingGroup = `-- name: ListSiblingGroup :many
SELECT id, name, description, due, parent_id, user_id, completed_at, estimate, position, snooze_until, goal_id FROM tasks
WHERE user_id = $1 AND parent_id IS NOT DISTINCT FROM $2
ORDER BY position, id
FOR UPDATE
`

type ListSiblingGroupParams struct {
	UserID   int64
	ParentID pgtype.Int8
}

func (q *Queries) ListSiblingGroup(ctx context.Context, arg ListSiblingGroupParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listSiblingGroup, arg.UserID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Due,
			&i.ParentID,
			&i.UserID,
			&i.CompletedAt,
			&i.Estimate,
			&i.Position,
			&i.SnoozeUntil,
			&i.GoalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, description, due, parent_id, user_id, completed_at, estimate, position, snooze_until, goal_id FROM tasks WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListTasks(ctx context.Context, userID int64) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Due,
			&i.ParentID,
			&i.UserID,
			&i.CompletedAt,
			&i.Estimate,
			&i.Position,
			&i.SnoozeUntil,
			&i.GoalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nearestAncestorGoal = `-- name: NearestAncestorGoal :one
WITH RECURSIVE ancestors AS (
    SELECT t.id, t.parent_id, t.goal_id, 1 AS depth
      FROM tasks t
      JOIN tasks seed ON t.id = seed.parent_id
     WHERE seed.id = $1 AND seed.user_id = $2 AND t.user_id = $2
    UNION ALL
    SELECT t.id, t.parent_id, t.goal_id, ancestors.depth + 1
      FROM tasks t
      JOIN ancestors ON t.id = ancestors.parent_id
     WHERE t.user_id = $2
)
SELECT (
    SELECT goal_id FROM ancestors WHERE goal_id IS NOT NULL ORDER BY depth LIMIT 1
)
`

type NearestAncestorGoalParams struct {
	ID     int64
	UserID int64
}

// Walks parent_id upward from $1 scoped to $2, tracks depth, and returns
// the goal_id of the closest strict ancestor that has one. Used by UpdateTask
// on a promotion-to-root, evaluated BEFORE the parent is rewritten.
// Always returns one row: NULL when there is no ancestor carrying a goal
// (top-level seed task, or every ancestor's goal_id is NULL).
func (q *Queries) NearestAncestorGoal(ctx context.Context, arg NearestAncestorGoalParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, nearestAncestorGoal, arg.ID, arg.UserID)
	var goal_id pgtype.Int8
	err := row.Scan(&goal_id)
	return goal_id, err
}

const setTaskEstimate = `-- name: SetTaskEstimate :one
UPDATE tasks SET estimate = $2 WHERE id = $1 AND user_id = $3 RETURNING id, name, description, due, parent_id, user_id, completed_at, estimate, position, snooze_until, goal_id
`

type SetTaskEstimateParams struct {
	ID       int64
	Estimate int16
	UserID   int64
}

func (q *Queries) SetTaskEstimate(ctx context.Context, arg SetTaskEstimateParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskEstimate, arg.ID, arg.Estimate, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
		&i.UserID,
		&i.CompletedAt,
		&i.Estimate,
		&i.Position,
		&i.SnoozeUntil,
		&i.GoalID,
	)
	return i, err
}

const setTaskGoal = `-- name: SetTaskGoal :one
UPDATE tasks SET goal_id = $3 WHERE id = $1 AND user_id = $2 RETURNING id, name, description, due, parent_id, user_id, completed_at, estimate, position, snooze_until, goal_id
`

type SetTaskGoalParams struct {
	ID     int64
	UserID int64
	GoalID pgtype.Int8
}

func (q *Queries) SetTaskGoal(ctx context.Context, arg SetTaskGoalParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskGoal, arg.ID, arg.UserID, arg.GoalID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
		&i.UserID,
		&i.CompletedAt,
		&i.Estimate,
		&i.Position,
		&i.SnoozeUntil,
		&i.GoalID,
	)
	return i, err
}

const taskExists = `-- name: TaskExists :one
SELECT EXISTS (SELECT 1 FROM tasks WHERE id = $1 AND user_id = $2) AS exists
`

type TaskExistsParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) TaskExists(ctx context.Context, arg TaskExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, taskExists, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const uncompleteTask = `-- name: UncompleteTask :one
UPDATE tasks
SET completed_at = NULL
WHERE id = $1 AND user_id = $2
RETURNING id, name, description, due, parent_id, user_id, completed_at, estimate, position, snooze_until, goal_id
`

type UncompleteTaskParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) UncompleteTask(ctx context.Context, arg UncompleteTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, uncompleteTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
		&i.UserID,
		&i.CompletedAt,
		&i.Estimate,
		&i.Position,
		&i.SnoozeUntil,
		&i.GoalID,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET name = $2, description = $3, due = $4, parent_id = $5, snooze_until = $7, goal_id = $8
WHERE id = $1 AND user_id = $6
RETURNING id, name, description, due, parent_id, user_id, completed_at, estimate, position, snooze_until, goal_id
`

type UpdateTaskParams struct {
	ID          int64
	Name        string
	Description string
	Due         pgtype.Timestamptz
	ParentID    pgtype.Int8
	UserID      int64
	SnoozeUntil pgtype.Timestamptz
	GoalID      pgtype.Int8
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Due,
		arg.ParentID,
		arg.UserID,
		arg.SnoozeUntil,
		arg.GoalID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
		&i.UserID,
		&i.CompletedAt,
		&i.Estimate,
		&i.Position,
		&i.SnoozeUntil,
		&i.GoalID,
	)
	return i, err
}

const updateTaskPosition = `-- name: UpdateTaskPosition :exec
UPDATE tasks SET position = $3 WHERE id = $1 AND user_id = $2
`

type UpdateTaskPositionParams struct {
	ID       int64
	UserID   int64
	Position int32
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error {
	_, err := q.db.Exec(ctx, updateTaskPosition, arg.ID, arg.UserID, arg.Position)
	return err
}
