// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pomodoro.sql

package db

import (
	"context"
)

const cancelActivePomodoro = `-- name: CancelActivePomodoro :one
UPDATE pomodoros SET end_at = NOW()
WHERE user_id = $1 AND end_at IS NULL
RETURNING id, user_id, task_id, start_at, end_at, complete
`

func (q *Queries) CancelActivePomodoro(ctx context.Context, userID int64) (Pomodoro, error) {
	row := q.db.QueryRow(ctx, cancelActivePomodoro, userID)
	var i Pomodoro
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.StartAt,
		&i.EndAt,
		&i.Complete,
	)
	return i, err
}

const completeActivePomodoro = `-- name: CompleteActivePomodoro :one
UPDATE pomodoros SET end_at = start_at + INTERVAL '25 minutes', complete = TRUE
WHERE user_id = $1 AND end_at IS NULL
RETURNING id, user_id, task_id, start_at, end_at, complete
`

func (q *Queries) CompleteActivePomodoro(ctx context.Context, userID int64) (Pomodoro, error) {
	row := q.db.QueryRow(ctx, completeActivePomodoro, userID)
	var i Pomodoro
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.StartAt,
		&i.EndAt,
		&i.Complete,
	)
	return i, err
}

const countCompletedPomodorosForTask = `-- name: CountCompletedPomodorosForTask :one
SELECT count(*)::bigint AS count FROM pomodoros WHERE task_id = $1 AND user_id = $2 AND complete
`

type CountCompletedPomodorosForTaskParams struct {
	TaskID int64
	UserID int64
}

func (q *Queries) CountCompletedPomodorosForTask(ctx context.Context, arg CountCompletedPomodorosForTaskParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedPomodorosForTask, arg.TaskID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActivePomodoro = `-- name: GetActivePomodoro :one
SELECT id, user_id, task_id, start_at, end_at, complete FROM pomodoros WHERE user_id = $1 AND end_at IS NULL
`

func (q *Queries) GetActivePomodoro(ctx context.Context, userID int64) (Pomodoro, error) {
	row := q.db.QueryRow(ctx, getActivePomodoro, userID)
	var i Pomodoro
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.StartAt,
		&i.EndAt,
		&i.Complete,
	)
	return i, err
}

const listPomodorosForTask = `-- name: ListPomodorosForTask :many
SELECT id, user_id, task_id, start_at, end_at, complete FROM pomodoros WHERE task_id = $1 AND user_id = $2 ORDER BY start_at
`

type ListPomodorosForTaskParams struct {
	TaskID int64
	UserID int64
}

func (q *Queries) ListPomodorosForTask(ctx context.Context, arg ListPomodorosForTaskParams) ([]Pomodoro, error) {
	rows, err := q.db.Query(ctx, listPomodorosForTask, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pomodoro
	for rows.Next() {
		var i Pomodoro
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.StartAt,
			&i.EndAt,
			&i.Complete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startPomodoro = `-- name: StartPomodoro :one
INSERT INTO pomodoros (user_id, task_id, start_at)
VALUES ($1, $2, NOW())
RETURNING id, user_id, task_id, start_at, end_at, complete
`

type StartPomodoroParams struct {
	UserID int64
	TaskID int64
}

func (q *Queries) StartPomodoro(ctx context.Context, arg StartPomodoroParams) (Pomodoro, error) {
	row := q.db.QueryRow(ctx, startPomodoro, arg.UserID, arg.TaskID)
	var i Pomodoro
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.StartAt,
		&i.EndAt,
		&i.Complete,
	)
	return i, err
}
