// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (name, description, due, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, due, parent_id
`

type CreateTaskParams struct {
	Name        string
	Description string
	Due         pgtype.Timestamptz
	ParentID    pgtype.Int8
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Name,
		arg.Description,
		arg.Due,
		arg.ParentID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :one
DELETE FROM tasks WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteTask, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getTask = `-- name: GetTask :one
SELECT id, name, description, due, parent_id FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, description, due, parent_id FROM tasks ORDER BY id
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Due,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskExists = `-- name: TaskExists :one
SELECT EXISTS (SELECT 1 FROM tasks WHERE id = $1) AS exists
`

func (q *Queries) TaskExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, taskExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET name = $2, description = $3, due = $4, parent_id = $5
WHERE id = $1
RETURNING id, name, description, due, parent_id
`

type UpdateTaskParams struct {
	ID          int64
	Name        string
	Description string
	Due         pgtype.Timestamptz
	ParentID    pgtype.Int8
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Due,
		arg.ParentID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentID,
	)
	return i, err
}
